### ISSUE TITLE
No forward with  Token_performer?

### ISSUE THREAD

**Issue by GuideWsp** [yitu-opensource/T2T-ViT#1]
I try to run the T2T-ViT, but meet a error: there is no forward on the Token_performer.
So will you provide the forward part code for Token_performer?
Hoping for your reply.

**Comment by yuanli2333** [comment]
Hi, we will release this part of codes ([Token_performer.py](https://github.com/yitu-opensource/T2T-ViT/blob/main/models/token_performer.py)) in the future. 
Currently, you can train or test all models that take Transformer as T2T transformer layer ([Token_transformer.py](https://github.com/yitu-opensource/T2T-ViT/blob/main/models/token_transformer.py)).

**Comment by GuideWsp** [comment]
OK, thanks,hoping it

**Comment by yuanli2333** [comment]
We will release the codes of Token_performer next week. Thanks for your patience.
