### ISSUE TITLE
the input channels

### ISSUE THREAD

**Issue by DDxk369** [yitu-opensource/T2T-ViT#13]
您好，非常感谢您开源这么棒的一个工作，我对t2t特别感兴趣，并且向将它应用于医疗方向的数据，但是这就需要把输入信道的维数从3更改为1，对您的工作正在学习当中，对很多代码还不是特别熟悉，所以在这里想问下您，在哪里可以设置输入信道的相关参数？
        谢谢！！！！

**Comment by yuanli2333** [comment]
The defaul value of input channel value for image  is 3，you can change the 'in_chans=3' in this [line](https://github.com/yitu-opensource/T2T-ViT/blob/097249357c177d0329e23fee981763897070890e/models/t2t_vit.py#L104).
