### ISSUE TITLE
The minor difference between Token_transformer class and  transformer_block.Block class

### ISSUE THREAD

**Issue by miraclebiu** [yitu-opensource/T2T-ViT#14]
when forwarding, Token_transformer:`x = self.attn(self.norm1(x))`
However, most Blocks are `x = x + self.drop_path(self.attn(self.norm1(x)))`

Is there a reason to do so ?

**Comment by yuanli2333** [comment]
In T2T transformer, the original 'x' has different dimmension with 'self.attn(self.norm1(x))' as we need reduce dimension in k,q,v to reduce FLOPs, we do skip connection on 'v' and 'self.attn(self.norm1(x))' as done in this [line](https://github.com/yitu-opensource/T2T-ViT/blob/097249357c177d0329e23fee981763897070890e/models/token_transformer.py#L41) .
