### ISSUE TITLE
visualization of resnet50 features

### ISSUE THREAD

**Issue by ming1993li** [yitu-opensource/T2T-ViT#16]
Hi, thank you for sharing your work with us. I have a question about the feature visualization of resnet50 in visualization-resnet.ipynb. In your codes, you just fetch the conv layers of resnet50 and pass the sample image into them sequentially. I think you should pass the sample image into "original" resnet50 and adopt operations like "register_forward_hook" to obtain the right outputs of targeted conv layers. Is that right?

**Comment by yuanli2333** [comment]
Hi, you are right. It would be better for visualization by using  'register_forward_hook'. But actually, the visualization results by directly fetching the conv layers or by adopting 'register_forward_hook' have little difference. So for simplicity, we directly pass image to conv layers sequentially.
