### ISSUE TITLE
can it be used for Object Detection?

### ISSUE THREAD

**Issue by coderHI328K** [yitu-opensource/T2T-ViT#18]
hello, I saw "class token" in your paper. Can this model be used for Object Detection? Or it can only be used for classification? Glad to hear response.

**Comment by yuanli2333** [comment]
Hi,
If you want to adopt T2T-ViT as backbone for object detection, you can use the 'class token' for classification and use 'other tokens' for bounding box regression, or just ignore 'class token',  and do both classification and bounding box regression on other tokens.
