### ISSUE TITLE
The released models seem broken and cannot be opened?

### ISSUE THREAD

**Issue by QiushiYang** [yitu-opensource/T2T-ViT#2]
Thanks a lot for sharing your codes. But it seems the T2T-ViT Models are broken and I can't open them. Would you like to upload them again? Many thanks :-)

**Comment by yuanli2333** [comment]
Hi, do you mean you can't load the models after downloading from google drive? 
What's type of error you have, could you provide more details about it?

**Comment by GuideWsp** [comment]
The pth.tar is not tar file, you can load it by torch.load('*.pth.tar')

> Thanks a lot for sharing your codes. But it seems the T2T-ViT Models are broken and I can't open them. Would you like to upload them again? Many thanks :-)

**Comment by QiushiYang** [comment]
Thank you all so much! I tried to use torch.load() and could load the model successfully.
