### ISSUE TITLE
The performance of only using Performer in the whole network

### ISSUE THREAD

**Issue by speedinghzl** [yitu-opensource/T2T-ViT#21]
Hi @yuanli2333, Nice work, and thanks for sharing.  T2T-ViT-7 uses the Performer in T2T module and the original Transformer in the backbone. Do you have results of using Performer in T2T module and the backbone both? Thanks.

**Comment by yuanli2333** [comment]
We haven't tried to use Performer in both T2T module and the backbone.
The Performer layer can reduce the requriement on GPU memory when the token length is large. In the backbone of original ViT, the token length is 196 or 256, which is not large and no need to adopt Performer layer in backbone as the Performer can cause performance degradation.

**Comment by speedinghzl** [comment]
@yuanli2333  Thanks.
