### ISSUE TITLE
Remove  classifier head

### ISSUE THREAD

**Issue by huixiancheng** [yitu-opensource/T2T-ViT#22]
First,thanks for the open source code.
I have a problem need help.
In Vit,We could remove the final MLP head and use reshape to get a  feature map(Not very correct description).Then we could use it to finish sem.seg  Like this pic and some arxiv papers have done.
![QQ截图20210222152605](https://user-images.githubusercontent.com/65054204/108675957-75c33f80-7522-11eb-8e26-78be47b9eb28.jpg)
Could T2T-VIT use similar way？
After **remove Classifier head** in **T2t_vit_t_24**, input **test=torch.randn(1,3,224,224)**，the output size of this model is **torch.Size([1, 512])**  
It's look like cannot simply reshape the feature with same way.
Since some operations in T2T model that i don't understand.
Could you give me some advice?

**Comment by yuanli2333** [comment]
After you remove the classifier head, the output is from the the class token with shape of [1, 512], if you want to use the hidden_features, you should use other 14x14 tokens, where each token corresponding to one patch. 
So you need change this [line](https://github.com/yitu-opensource/T2T-ViT/blob/fecacc47acdb49001854b82196e8b4ba8c77fd89/models/t2t_vit.py#L168):

from
```
return x[:, 0]
```
to 
```
return x[:, 1:] 
```
thus the hidden feature has a size [n_patch, D], namely [196, 512] for T2T-ViTt-24.

**Comment by huixiancheng** [comment]
thanks for your quick reply.:thumbsup:  I will take a try.:running:
