### ISSUE TITLE
Confusion matrix and classify validation images?

### ISSUE THREAD

**Issue by ilem777** [yitu-opensource/T2T-ViT#27]
Hello, can the program plot the confusion matrix? This way I can know the accuracy rate for each category. Also, can I test a few images randomly to see the results of the completed training model recognition? Thank you.

**Comment by yuanli2333** [comment]
Hi, I would do this after some ddl.
For testing single image, of course you can use our model, just load the model and images correctly, then do inference as validation.

**Comment by ilem777** [comment]
@yuanli2333 Thanks, looking forward to it.
