### ISSUE TITLE
Transfer learning CIFAR10

### ISSUE THREAD

**Issue by aldahdooh** [yitu-opensource/T2T-ViT#29]
Following your code, how to do transfer learning for CIFAR10?

**Comment by yuanli2333** [comment]
We will release the results of transfer learning in the future.

**Comment by aldahdooh** [comment]
@yuanli2333 Many thanks for your feedback. You mean in near future, or it will take a while?

**Comment by yuanli2333** [comment]
Busy this period, maybe one month later.

**Comment by yuanli2333** [comment]
Have released the codes of transfer learning as 'transfer_learning.py'.
