### ISSUE TITLE
RuntimeError: invalid argument 5: k not in range for dimension at /pytorch/aten/src/THC/generic/THCTensorTopK.cu:26

### ISSUE THREAD

**Issue by DDxk369** [yitu-opensource/T2T-ViT#3]
不好意思，为什么当我想把数据集换成三分类、channel是1的数据时，会如此报错：
Training with a single process on 1 GPUs.
adopt transformer encoder for tokens-to-token
Model T2t_vit_t_14 created, param count: 21157225
Data processing configuration for current model + dataset:
	input_size: (3, 224, 224)
	interpolation: bicubic
	mean: (0.485, 0.456, 0.406)
	std: (0.229, 0.224, 0.225)
	crop_pct: 0.9
Using native Torch AMP. Training in mixed precision.
Scheduled epochs: 110
Train: 0 [   0/45 (  0%)]  Loss:  1.081793 (1.0818)  Time: 4.070s,   15.72/s  (4.070s,   15.72/s)  LR: 1.000e-06  Data: 2.485 (2.485)
Train: 0 [  44/45 (100%)]  Loss:  1.033082 (1.0813)  Time: 0.834s,   76.75/s  (0.764s,   83.82/s)  LR: 1.000e-06  Data: 0.164 (0.066)
Traceback (most recent call last):
  File "main.py", line 764, in <module>
    main()
  File "main.py", line 567, in main
    eval_metrics = validate(model, loader_eval, validate_loss_fn, args, amp_autocast=amp_autocast)
  File "main.py", line 730, in validate
    acc1, acc5 = accuracy(output, target, topk=(1, 5))
  File "/usr/local/lib/python3.6/dist-packages/timm/utils/metrics.py", line 29, in accuracy
    _, pred = output.topk(maxk, 1, True, True)
RuntimeError: invalid argument 5: k not in range for dimension at /pytorch/aten/src/THC/generic/THCTensorTopK.cu:26

**Comment by yuanli2333** [comment]
Your dataset only have 3 categories, so there is no top5 accuracy. You should only test top1 accuracy by changing the topk=(1,5)  to topk=(1,)

**Comment by DDxk369** [comment]
Thank you very much for your answer
