### ISSUE TITLE
How the "kernel_ratio" influences the performance?

### ISSUE THREAD

**Issue by PkuRainBow** [yitu-opensource/T2T-ViT#30]
Really nice work! I am wondering how the "kernel_ratio" of **Token_performer** influences the final performance.

https://github.com/yitu-opensource/T2T-ViT/blob/9dafdef17f6740fc600dad754e0f40bd246463e0/models/token_performer.py#L9

**Comment by yuanli2333** [comment]
Hi,
It has a few influences on the final performance when kernel_ration>=0.5. Based on our experiments, please don't use kernel_ration<0.5. We would update the analysis in our next arxiv verion.
