### ISSUE TITLE
Fine-tuning

### ISSUE THREAD

**Issue by davidmoralesrodriguez** [yitu-opensource/T2T-ViT#32]
Hi, is it possible to fine-tune a model on a custom dataset using the pretrained imagenet models?

**Comment by yuanli2333** [comment]
Of course, it can.
Simply, you can:

```
from timm.models import create_model

model = = create_model(
    args.model,
    pretrained=args.pretrained,
    num_classes=args.num_classes,
    drop_rate=args.drop,
    drop_connect_rate=args.drop_connect,  # DEPRECATED, use drop_path
    drop_path_rate=args.drop_path,
    drop_block_rate=args.drop_block,
    global_pool=args.gp,
    bn_tf=args.bn_tf,
    bn_momentum=args.bn_momentum,
    bn_eps=args.bn_eps,
    checkpoint_path=args.initial_checkpoint,
    img_size=args.img_size)
```

I will update the codes of how to finetune on other datasets like CIFAR10/100 recently.

**Comment by yuanli2333** [comment]
We released the codes of finetune our model on CIFAR10/100 in 'transfer_learning.py'. 
You can also use these lines to load our model and pretrained paramters:
[line1](https://github.com/yitu-opensource/T2T-ViT/blob/518a84ba9fe1c8d428a83bb4598c7911bb58429f/transfer_learning.py#L117)
[line2](https://github.com/yitu-opensource/T2T-ViT/blob/518a84ba9fe1c8d428a83bb4598c7911bb58429f/transfer_learning.py#L134)
