### ISSUE TITLE
Local variable 'input' referenced before assignment

### ISSUE THREAD

**Issue by laohanlin** [yitu-opensource/T2T-ViT#34]
I want to run your code. But no matter how I modify it, timm keeps telling me local variable 'input' referenced before assignment. As is shown in the picture:
![image](https://user-images.githubusercontent.com/71748257/111157443-d8fc3b00-85d1-11eb-80c3-603eeae8edfd.png)

**Comment by yuanli2333** [comment]
What's the timm version you used?
Please installl timm 3.4.0 by: pip install timm==0.3.4
