### ISSUE TITLE
forward

### ISSUE THREAD

**Issue by STICK1996** [yitu-opensource/T2T-ViT#4]
def forward(self,x,**kwargs):
     
   
 print(x[0].shape)
        # shape = x[0].shape#torch.Size([3, 224, 224])
        # x = torch.stack(x,1).view(-1,shape[-3],shape[-2],shape[-1])
        # x = x.view(-1, x.size(-3), x.size(-2), x.size(-1))  # Tensor_resize
        print(x.shape)#torch.Size([8, 3, 224, 224])
        x = self.base(x)       # base_model = T2t_vit_t_19(pretrained=False)

        print(x.shape)
        x = x.view(x.size(0), -1)
TypeError: forward() takes 1 positional argument but 2 were given

**Comment by STICK1996** [comment]
@cypw How to solve the above problems

**Comment by yuanli2333** [comment]
Please describe your problem with more suitable way or more details.
