### ISSUE TITLE
Questions about the results of the experiment

### ISSUE THREAD

**Issue by chenyucong1** [yitu-opensource/T2T-ViT#41]
Hi author, why is the accuracy and loss of test so different from the data of EMA?
![微信图片_20210330153816](https://user-images.githubusercontent.com/80387024/112951479-f999c880-916d-11eb-9310-a8a8c7f1c05f.png)

**Comment by yuanli2333** [comment]
Hi, it seems that the '--model-ema-decay' is not suitable. 
So you can:
(1). disable --model-ema;
(2). change the value of '--model-ema-decay'  based on your iteration number in training.
