### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Summer-sss** [yitu-opensource/T2T-ViT#46]
Where should the data set be placed, and where should the pre-training model be used? Thank you very much for your reply.

**Comment by yuanli2333** [comment]
Hi, if you are talk about the transfer learning on CIFAR10/100, you don't need download dataset, our codes can download it automatically, and the pretrained models are in [here](https://github.com/yitu-opensource/T2T-ViT#2-t2t-vit-models).
