### ISSUE TITLE
resizing images for feature visualization

### ISSUE THREAD

**Issue by kahnchana** [yitu-opensource/T2T-ViT#48]
Hi, I'm really interested in this work, and was looking at the feature visualization section. 

In this [code](https://github.com/yitu-opensource/T2T-ViT/blob/main/visualization_vit.ipynb), how do you feed larger size images to the model? (e.g. 512 to 384 VIT) Do you make any modifications?

**Comment by yuanli2333** [comment]
Hi,

You can interpolate the position embedding for different image size with the function [here](https://github.com/yitu-opensource/T2T-ViT/blob/9f6c2b3657c68f7afd7a31562072e4f976154368/utils.py#L27).

Or directly use T2T-ViT as the way in the [usage](https://github.com/yitu-opensource/T2T-ViT#usage), we already put the interpolation function in the function of 'load_for_transfer_learning'.

**Comment by kahnchana** [comment]
Thanks a lot for the info. Got it working.
