### ISSUE TITLE
How to calculate MACs?

### ISSUE THREAD

**Issue by pengzhiliang** [yitu-opensource/T2T-ViT#5]
Thank u very much!
How do you calculate MACs? by using the thop package or other ? and can you release the code?

**Comment by yuanli2333** [comment]
Hi, you can calculate the MACs by using [thop](https://github.com/Lyken17/pytorch-OpCounter) package, but the results will be lower than the real MACs. We use the script in [Google Electra](https://github.com/google-research/electra/blob/master/flops_computation.py). But this script only compute the FLOPs, which should be 2x of MACs, and you should reset the paramters in this script.

**Comment by pengzhiliang** [comment]
OK, I'll have a try. Thank u~
