### ISSUE TITLE
Larger models learn slowly?

### ISSUE THREAD

**Issue by chenwydj** [yitu-opensource/T2T-ViT#50]
Dear authors,

Thank you very much for this great repo!

I am training larger models (T2T-ViT-19/24, etc.), and I find during training their accuracies increase slower than small models like T2T-ViT-7. Is this an expected behavior?

Thank you!

**Comment by yuanli2333** [comment]
Hi, large model would converge slower at first 10 to 20 epochs, but will increase faster after the initial stages.

**Comment by chenwydj** [comment]
Thank you!
