### ISSUE TITLE
could you share the log of training T2T-ViT_t-24 and T2T-ViT_t-19?

### ISSUE THREAD

**Issue by wangpichao** [yitu-opensource/T2T-ViT#54]
Thanks for your wonderful work, and I wonder whether you could share the log of training T2T-ViT_t-24 and T2T-ViT_t-19? As I want to compare my method with yours from the training point. Many thanks.

**Comment by yuanli2333** [comment]
Hi, uploaded the logs: [log_t2t_t_vit_19](https://github.com/yitu-opensource/T2T-ViT/releases/download/main/log_t2t_t_vit_19.csv) and [log_t2t_t_vit_24](https://github.com/yitu-opensource/T2T-ViT/releases/download/main/log_t2t_t_vit_24.csv)

**Comment by wangpichao** [comment]
> Hi, uploaded the logs: [log_t2t_t_vit_19](https://github.com/yitu-opensource/T2T-ViT/releases/download/main/log_t2t_t_vit_19.csv) and [log_t2t_t_vit_24](https://github.com/yitu-opensource/T2T-ViT/releases/download/main/log_t2t_t_vit_24.csv)

Thanks very much.
