### ISSUE TITLE
I have a problem about input size ?

### ISSUE THREAD

**Issue by muzishen** [yitu-opensource/T2T-ViT#7]
Thank you very much for your excellent work. 
When I finetune the T2T-ViT, whether the input size must be fixed into the your size (i.e., 224 x 224) of the pre-training model.
Is there a way to solve this limiting problem ?

**Comment by yuanli2333** [comment]
For finetuning, you can change the input size, but you also need modify the length of position embedding. And if your input size is not a square (hight!=width), you should modify [this line](https://github.com/yitu-opensource/T2T-ViT/blob/097249357c177d0329e23fee981763897070890e/models/t2t_vit.py#L78) .
