### ISSUE TITLE
Only use the first patch after T2T-ViT Backbone

### ISSUE THREAD

**Issue by JingXfei** [yitu-opensource/T2T-ViT#8]
Hello and thanks for your excellent work!
However, I don't understand why only the first patch is used after T2T-ViT Backbone?

https://github.com/yitu-opensource/T2T-ViT/blob/b873c90f890522822b2c67b519fa13283e2287e8/models/t2t_vit.py#L166

**Comment by yuanli2333** [comment]
The first one is not the first patch, but the class token for classification, as in [this line](https://github.com/yitu-opensource/T2T-ViT/blob/097249357c177d0329e23fee981763897070890e/models/t2t_vit.py#L158).
