### ISSUE TITLE
显存随着训练的进行不断增长

### ISSUE THREAD

**Issue by shinianzhihou** [yitu-opensource/T2T-ViT#9]
你好，我在第1个epoch训练结束后，训练第二个epoch发现显存增长，然后在第三个epoch的时候显存爆了。
请问这是正常的吗？

**Comment by yuanli2333** [comment]
是正常的，现在的显存占用会很大，因为我们在T2T module中使用的是Transformer layer，我们会在下周发布在T2T module中使用Performer layer的代码。

**Comment by shinianzhihou** [comment]
你好～新年快乐～and期待Performer的代码release～

**Comment by yuanli2333** [comment]
新年快乐～这周会release

**Comment by miraclebiu** [comment]
> 是正常的，现在的显存占用会很大，因为我们在T2T module中使用的是Transformer layer，我们会在下周发布在T2T module中使用Performer layer的代码。

从开始训练到结束训练，显存增长大概会增长多少？我训练的时候也遇到了这个问题

**Comment by zjhdxh** [comment]
> > 是正常的，现在的显存占用会很大，因为我们在T2T module中使用的是Transformer layer，我们会在下周发布在T2T module中使用Performer layer的代码。
> 
> 从开始训练到结束训练，显存增长大概会增长多少？我训练的时候也遇到了这个问题

我也遇到了这样的问题，每过一会显存就会涨一点。
